Project review session
hydaline-code/Code-review-project pull request #1
Opened 2023-02-20 10:59 UTC by hydaline-code

Hi Everyone. Here we are asked to play the role of the code reviewer accordingly . Please kindly assist and correct my code review exercise. Thanks

2023-02-20 11:15 UTC, hydaline-code reviewed
Linter Checks passing 
Good use of  workflow

2023-02-20 11:15 UTC, hydaline-code commented on index.html
> +    <div class="container">
Kindly use section before div for a div a semantically a child of a section not accurate placing a section inside a div

2023-02-20 11:15 UTC, hydaline-code commented on index.html
> +            <h2>Premium Materials</h2>
Due to SEO accurracy it would be better if you follow the hierarchical order of the heading (h1, h2.....).

2023-02-20 11:15 UTC, hydaline-code commented on index.html
> +        <div class="product" id="valve">
Please kindly  consider here it is not quite professional to use a class and id to target the same tag except for some exceptional styling

2023-02-20 11:15 UTC, hydaline-code commented on style.css
> +  display: flex;
kindly review the way you presented your properties

2023-02-20 11:42 UTC, Shedrack-Sunday requested changes
Hi @hydaline-code     👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


Highlights
✅All linters are checked
✅ Descriptive commit messages 
  
Required Changes ♻️

- [x] Firstly, your summary looks very short, and if you agree with me, it's not quite professional 😉 . Please use my summary here as a reference, to make your review reference detailed and professional 👍 
- [ ] Secondly, You did a good job on the reviews, but I'll advise you frequently use to emojis to show friendliness and Grammarly for proper sentence structure 👏 

_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-20 11:42 UTC, Shedrack-Sunday commented on index.html
> +    <div class="container">
- [ ] Kindly use the back string to make your tag uniquely identified. use `section` `div` instead. 
- [ ] I advise you use Grammarly to structure your sentence, thereby giving more reasons why you asked for such change clearly 👍

2023-02-20 11:42 UTC, Shedrack-Sunday commented on index.html
> +            <h2>Premium Materials</h2>
- [ ] Also in this section, you did great. however, the `hx` hierarchy was followed because it's an `h2` tag. Please always be detailed enough on the suggestions you made, and why you asked for such suggestions 👍

2023-02-20 12:49 UTC, Alfredbis29 requested changes
Hi @hydaline-code , 

Good job so far, I can see that you put in a lot of energy into this :+1: 
However, there are some few issues you need to work on in order to proceed to the next project, but believe me, you are almost there. 

 ![soclose](https://user-images.githubusercontent.com/97100091/205930721-3967bc84-4b21-4cec-830a-b6844fe2b36f.gif) 

## Highlights 

- Used GitHub's 'Review changes' feature from GitHub :heavy_check_mark: 
- Wrote at least 2 comments in the review :heavy_check_mark:  
- Utilised GitHub's inline comments feature for reviews :heavy_check_mark: 

## Required Changes :recycle: 

- [ ] This has not been addressed yet but was required in the previous review, You can use a couple of emojis and/or gifs to make the review more human-friendly. Kindly check and make sure they are. :wink:  :smile: 

- [ ] You left the call to be tagged in case of any concern or question, which is an indication that you did not use the correct review template. as said in the previous review : "Firstly, your summary looks very short, and if you agree with me, it's not quite professional: wink: . Please use my summary here as a reference, to make your review reference detailed and professional"  [use this template here as exemple to make a professional summary](https://github.com/hydaline-code/Code-review-project/pull/1#pullrequestreview-1305607525)


## Optional Suggestions




- [ ] Kindly phrase your comments in a polite and considerate manner, like a suggestion, instead of a command. This will make it easy for the student to accept and implement them.


Cheers and Happy coding :clap: :clap: :clap: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @alfredbis29 in your question so I can receive the notification.


#### Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

#
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-20 12:49 UTC, Alfredbis29 commented on style.css
> +  display: flex;
- [OPTIONAL ] I can see that you made a great review , but I don't understand this one  "kindly review the way you presented your properties" , kindly be specific and explicite in what you are requesting , this will help student to understand your requests changes . :wink:

2023-02-20 12:49 UTC, Alfredbis29 commented on index.html
> +        <div class="product" id="valve">
- [ ] I can see that you have done the changes asked in the previous review, but you forgot to add the emojis. Please think about doing so to be more approachable and humane. :wink:

2023-02-24 15:41 UTC, hydaline-code commented on index.html
> +        <div class="product" id="valve">
Good implementing #id👍but  there is no use of your #id valve or bass from your styling file. Please it is not very professional to use both a class and an id attribute on the same tag🤞. Kindly review and do some corrections Thanks.👍

2023-02-24 15:41 UTC, hydaline-code commented on style.css
> +  display: flex;
👍Good implementing lists type in your work but it will look more organized and presentable 😍 if you respect the order of the appearance following your HTML file to enable your CSS easily readable. 👌

2023-02-24 15:41 UTC, hydaline-code commented on index.html
> +    <div class="container">
A <section/> represents a generic section of a document i.e a grouping of content and a <div> are child elements that are found inside a section.👍👍 Hence I suggest you kindly correct the order in which you have placed them. 🥰Thanks

2023-02-24 16:12 UTC, TadesseDev approved these changes
### Hi @hydaline-code 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)



## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. ✅
## Optional suggestions
- [Optional] Please try to be clear in your summary. You should summarize you're review and comments in your review summary section. currently your summery doesn't say what you have found out in your review.
- [Optional] It would be wise to use a couple of emojis and/or gifs in the review summary. This will make your review more friendly
- [Optional] Try to be more detailed in your comments, explain more and provide some links that could help in resolving/understanding the issue.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 20:15 UTC, merged